from django.contrib.auth.decorators import login_required
from django.urls import path

from . import views

urlpatterns = [
    path(
        "",
        login_required(views.index),
        name="index",
    ),
    path(
        "company-autocomplete",
        login_required(
            views.CompanyAutocomplete.as_view(
                create_field="name", validate_create=True
            )
        ),
        name="company-autocomplete",
    ),
    path(
        "tag-category-autocomplete",
        login_required(
            views.TagCategoryAutocomplete.as_view(
                create_field="name", validate_create=True
            )
        ),
        name="tag-category-autocomplete",
    ),
    path(
        "tag-autocomplete",
        login_required(views.TagAutocomplete.as_view()),
        name="tag-autocomplete",
    ),
    path(
        "job_descriptions",
        login_required(views.JobDescriptionListView.as_view()),
        name="job_description_list",
    ),
    path(
        "job_descriptions/add/",
        login_required(views.JobDescriptionCreateView.as_view()),
        name="job_description_add",
    ),
    path(
        "job_descriptions/edit/<int:pk>/",
        login_required(views.JobDescriptionUpdateView.as_view()),
        name="job_description_edit",
    ),
    path(
        "job_descriptions/details/<int:pk>/",
        login_required(views.JobDescriptionDetailView.as_view()),
        name="job_description_details",
    ),
    path(
        "job_descriptions/delete/<int:pk>/",
        login_required(views.JobDescriptionDeleteView.as_view()),
        name="job_description_delete",
    ),
    path(
        "tags",
        login_required(views.TagListView.as_view()),
        name="tag_list",
    ),
    path(
        "tags/add/",
        login_required(views.TagCreateView.as_view()),
        name="tag_add",
    ),
    path(
        "tags/edit/<int:pk>/",
        login_required(views.TagUpdateView.as_view()),
        name="tag_edit",
    ),
    path(
        "tags/details/<int:pk>/",
        login_required(views.TagDetailView.as_view()),
        name="tag_details",
    ),
    path(
        "tags/delete/<int:pk>/",
        login_required(views.TagDeleteView.as_view()),
        name="tag_delete",
    ),
    path(
        "tags/bulk_import/",
        login_required(views.TagBulkImportView.as_view()),
        name="tag_bulk_import",
    ),
    path(
        "companies",
        login_required(views.CompanyListView.as_view()),
        name="company_list",
    ),
    path(
        "companies/add/",
        login_required(views.CompanyCreateView.as_view()),
        name="company_add",
    ),
    path(
        "companies/edit/<int:pk>/",
        login_required(views.CompanyUpdateView.as_view()),
        name="company_edit",
    ),
    path(
        "companies/details/<int:pk>/",
        login_required(views.CompanyDetailView.as_view()),
        name="company_details",
    ),
    path(
        "companies/delete/<int:pk>/",
        login_required(views.CompanyDeleteView.as_view()),
        name="company_delete",
    ),
    path(
        "resume_jobs",
        login_required(views.ResumeJobListView.as_view()),
        name="resume_job_list",
    ),
    path(
        "resume_jobs/add/",
        login_required(views.ResumeJobCreateView.as_view()),
        name="resume_job_add",
    ),
    path(
        "resume_jobs/edit/<int:pk>/",
        login_required(views.ResumeJobUpdateView.as_view()),
        name="resume_job_edit",
    ),
    path(
        "resume_jobs/details/<int:pk>/",
        login_required(views.ResumeJobDetailView.as_view()),
        name="resume_job_details",
    ),
    path(
        "resume_jobs/delete/<int:pk>/",
        login_required(views.ResumeJobDeleteView.as_view()),
        name="resume_job_delete",
    ),
    path(
        "resumes",
        login_required(views.ResumeListView.as_view()),
        name="resume_list",
    ),
    path(
        "resumes/add/",
        login_required(views.ResumeCreateView.as_view()),
        name="resume_add",
    ),
    path(
        "resumes/edit/<int:pk>/",
        login_required(views.ResumeUpdateView.as_view()),
        name="resume_edit",
    ),
    path(
        "resumes/details/<int:pk>/",
        login_required(views.ResumeDetailView.as_view()),
        name="resume_details",
    ),
    path(
        "resumes/delete/<int:pk>/",
        login_required(views.ResumeDeleteView.as_view()),
        name="resume_delete",
    ),
    path(
        "resume_education",
        login_required(views.ResumeEducationListView.as_view()),
        name="resume_education_list",
    ),
    path(
        "resume_education/add/",
        login_required(views.ResumeEducationCreateView.as_view()),
        name="resume_education_add",
    ),
    path(
        "resume_education/edit/<int:pk>/",
        login_required(views.ResumeEducationUpdateView.as_view()),
        name="resume_education_edit",
    ),
    path(
        "resume_education/details/<int:pk>/",
        login_required(views.ResumeEducationDetailView.as_view()),
        name="resume_education_details",
    ),
    path(
        "education/delete/<int:pk>/",
        login_required(views.ResumeEducationDeleteView.as_view()),
        name="resume_education_delete",
    ),
    path(
        "tag_categories",
        login_required(views.TagCategoryListView.as_view()),
        name="tag_category_list",
    ),
    path(
        "tag_categories/add/",
        login_required(views.TagCategoryCreateView.as_view()),
        name="tag_category_add",
    ),
    path(
        "tag_categories/edit/<int:pk>/",
        login_required(views.TagCategoryUpdateView.as_view()),
        name="tag_category_edit",
    ),
    path(
        "tag_categories/details/<int:pk>/",
        login_required(views.TagCategoryDetailView.as_view()),
        name="tag_category_details",
    ),
    path(
        "tag_categories/delete/<int:pk>/",
        login_required(views.TagCategoryDeleteView.as_view()),
        name="tag_category_delete",
    ),
]
