# Generated by Django 4.2.3 on 2023-07-31 02:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cv', '0003_rename_experiencepoint_experience_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Experience',
            new_name='ExperiencePoint',
        ),
        migrations.RenameModel(
            old_name='HistoricalExperience',
            new_name='HistoricalExperiencePoint',
        ),
        migrations.AlterModelOptions(
            name='historicalexperiencepoint',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical experience point', 'verbose_name_plural': 'historical experience points'},
        ),
    ]
