# Generated by Django 4.2.3 on 2023-07-31 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_rename_experience_experiencepoint_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltag',
            name='title',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='title',
        ),
        migrations.AddField(
            model_name='historicaltag',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='tag',
            name='name',
            field=models.CharField(blank=True, max_length=120, unique=True),
        ),
    ]
