# Generated by Django 4.2.3 on 2023-07-31 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0006_company_jobdescription_historicaljobdescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaljobdescription',
            name='raw_text',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='raw_text',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
