# Generated by Django 4.2.3 on 2023-08-02 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0007_historicaljobdescription_raw_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='historicalcompany',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Company', 'verbose_name_plural': 'historical Companies'},
        ),
        migrations.RenameField(
            model_name='experiencepoint',
            old_name='details',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='historicalexperiencepoint',
            old_name='details',
            new_name='name',
        ),
    ]
