# Generated by Django 4.2.3 on 2023-08-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0008_alter_company_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaljobdescription',
            name='raw_text',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='raw_text',
            field=models.TextField(max_length=5000, null=True),
        ),
    ]
