# Generated by Django 4.2.3 on 2023-08-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0009_alter_historicaljobdescription_raw_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdescription',
            name='tags',
            field=models.ManyToManyField(to='cv.tag'),
        ),
    ]
