# Generated by Django 4.2.3 on 2023-08-04 14:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0011_synonym_historicalsynonym_tag_synonyms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='synonym',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='synonym',
            name='last_edited_by',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='synonyms',
        ),
        migrations.AddField(
            model_name='historicaltag',
            name='keywords',
            field=models.CharField(max_length=500, null=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Username must be Alphanumeric', regex='^[a-zA-Z0-9]*$')]),
        ),
        migrations.AddField(
            model_name='tag',
            name='keywords',
            field=models.CharField(max_length=500, null=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Username must be Alphanumeric', regex='^[a-zA-Z0-9]*$')]),
        ),
        migrations.DeleteModel(
            name='HistoricalSynonym',
        ),
        migrations.DeleteModel(
            name='Synonym',
        ),
    ]
