# Generated by Django 4.2.3 on 2023-08-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0012_remove_synonym_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltag',
            name='name',
            field=models.CharField(db_index=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
