# Generated by Django 4.2.3 on 2023-08-04 14:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0013_alter_historicaltag_name_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltag',
            name='keywords',
            field=models.CharField(max_length=500, validators=[django.core.validators.RegexValidator(code='invalid_comma_separation', message='Keywords must be separated by commas', regex='^[0-9a-zA-Z\\s]+(,[0-9a-zA-Z\\s]+)*$')]),
        ),
        migrations.AlterField(
            model_name='tag',
            name='keywords',
            field=models.CharField(max_length=500, validators=[django.core.validators.RegexValidator(code='invalid_comma_separation', message='Keywords must be separated by commas', regex='^[0-9a-zA-Z\\s]+(,[0-9a-zA-Z\\s]+)*$')]),
        ),
    ]
