# Generated by Django 4.2.3 on 2023-08-05 05:47

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0015_remove_resume_experience_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalresumejob',
            name='updated_at',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='resumejob',
            name='updated_at',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False),
        ),
    ]
