# Generated by Django 4.2.3 on 2023-08-05 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0018_remove_experiencepoint_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalresumejob',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Job', 'verbose_name_plural': 'historical Jobs'},
        ),
        migrations.AlterModelOptions(
            name='historicalresumejobduty',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Job Duty', 'verbose_name_plural': 'historical Job Duties'},
        ),
        migrations.AlterModelOptions(
            name='resumejob',
            options={'verbose_name': 'Job', 'verbose_name_plural': 'Jobs'},
        ),
        migrations.AlterModelOptions(
            name='resumejobduty',
            options={'verbose_name': 'Job Duty', 'verbose_name_plural': 'Job Duties'},
        ),
        migrations.RemoveField(
            model_name='resumejob',
            name='job_duties',
        ),
        migrations.AddField(
            model_name='historicalresumejobduty',
            name='job',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cv.resumejob'),
        ),
        migrations.AddField(
            model_name='resumejobduty',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cv.resumejob'),
        ),
    ]
