# Generated by Django 4.2.3 on 2023-08-05 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0019_alter_historicalresumejob_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumejobduty',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.resumejob'),
        ),
    ]
