# Generated by Django 4.2.3 on 2023-08-05 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0020_alter_resumejobduty_job'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalresumejobduty',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Job duty', 'verbose_name_plural': 'historical Job duties'},
        ),
        migrations.AlterModelOptions(
            name='resumejobduty',
            options={'verbose_name': 'Job duty', 'verbose_name_plural': 'Job duties'},
        ),
        migrations.AlterField(
            model_name='resumejobduty',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_duties', to='cv.resumejob'),
        ),
    ]
