# Generated by Django 4.2.3 on 2023-08-05 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0021_alter_historicalresumejobduty_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalresumejob',
            name='job_duty_raw_text',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='resumejob',
            name='job_duty_raw_text',
            field=models.TextField(max_length=5000, null=True),
        ),
    ]
