# Generated by Django 4.2.3 on 2023-08-05 12:16

import cv.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0023_alter_historicalresumejob_job_duty_raw_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalresume',
            name='education',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='historicalresume',
            name='skills',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='historicalresumejob',
            name='job_duty_raw_text',
            field=models.TextField(max_length=5000, validators=[cv.models.job_duty_validator]),
        ),
        migrations.AlterField(
            model_name='resume',
            name='education',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='skills',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='resumejob',
            name='job_duty_raw_text',
            field=models.TextField(max_length=5000, validators=[cv.models.job_duty_validator]),
        ),
    ]
