# Generated by Django 4.2.3 on 2023-08-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0029_alter_historicalresumeeducation_end_at_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalresumeeducation',
            name='start_at_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resumeeducation',
            name='start_at_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
