# Generated by Django 4.2.3 on 2023-08-07 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0031_tagcategory_historicaltagcategory_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicaltagcategory',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Tag category', 'verbose_name_plural': 'historical Tag categories'},
        ),
        migrations.AlterModelOptions(
            name='tagcategory',
            options={'verbose_name': 'Tag category', 'verbose_name_plural': 'Tag categories'},
        ),
        migrations.AddField(
            model_name='historicaltag',
            name='show_in_cv',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='show_in_cv',
            field=models.BooleanField(default=True),
        ),
    ]
