# Generated by Django 4.2.3 on 2023-08-07 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0034_remove_historicalresume_skills_remove_resume_skills_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='skills',
            field=models.ManyToManyField(to='cv.tagcategory'),
        ),
    ]
