# Generated by Django 4.2.3 on 2023-08-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0037_alter_historicalresumeeducation_end_at_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltag',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='historicaltagcategory',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='tagcategory',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
